O = \
source/smarties/Communicator.o\
source/smarties/Core/Launcher.o\
source/smarties/Core/Master.o\
source/smarties/Core/StateAction.o\
source/smarties/Core/Worker.o\
source/smarties/Engine.o\
source/smarties/Learners/ACER.o\
source/smarties/Learners/AlgoFactory.o\
source/smarties/Learners/CMALearner.o\
source/smarties/Learners/DPG.o\
source/smarties/Learners/DQN.o\
source/smarties/Learners/Learner_approximator.o\
source/smarties/Learners/Learner.o\
source/smarties/Learners/MixedPG.o\
source/smarties/Learners/NAF.o\
source/smarties/Learners/PPO.o\
source/smarties/Learners/RACER.o\
source/smarties/Network/Approximator.o\
source/smarties/Network/Builder.o\
source/smarties/Network/CMA_Optimizer.o\
source/smarties/Network/Network.o\
source/smarties/Network/Optimizer.o\
source/smarties/ReplayMemory/DataCoordinator.o\
source/smarties/ReplayMemory/Episode.o\
source/smarties/ReplayMemory/MemoryBuffer.o\
source/smarties/ReplayMemory/MemoryProcessing.o\
source/smarties/ReplayMemory/Sampling.o\
source/smarties/Settings/ExecutionInfo.o\
source/smarties/Settings/HyperParameters.o\
source/smarties/smarties_extern.o\
source/smarties/Utils/DelayedReductor.o\
source/smarties/Utils/Profiler.o\
source/smarties/Utils/StatsTracker.o\
source/smarties/Utils/Warnings.o\

