O = \
core/3rd_party/dictionary.o\
core/3rd_party/finiparser.o\
core/3rd_party/iniparser.o\
core/bdry.o\
core/byte_mpi.o\
core/byte.o\
core/calcz.o\
core/chelpers.o\
core/coef.o\
core/comm_mpi.o\
core/conduct.o\
core/connect1.o\
core/connect2.o\
core/convect2.o\
core/convect.o\
core/crs_amg.o\
core/crs_hypre.o\
core/crs_xxt.o\
core/cvode_driver.o\
core/dictionary.o\
core/drive1.o\
core/drive2.o\
core/dssum.o\
core/edgec.o\
core/eigsolv.o\
core/fast3d.o\
core/fasts.o\
core/fcrs.o\
core/fem_amg_preco.o\
core/finiparser.o\
core/gauss.o\
core/genxyz.o\
core/gfldr.o\
core/gmres.o\
core/hmholtz.o\
core/hpf.o\
core/hsmg.o\
core/ic.o\
core/induct.o\
core/iniparser.o\
core/interp.o\
core/makeq_aux.o\
core/makeq.o\
core/map2.o\
core/math.o\
core/mpi_dummy.o\
core/multimesh.o\
core/mvmesh.o\
core/mxm_std.o\
core/mxm_wrapper.o\
core/navier0.o\
core/navier1.o\
core/navier2.o\
core/navier3.o\
core/navier4.o\
core/navier5.o\
core/navier6.o\
core/navier7.o\
core/navier8.o\
core/nek_in_situ.o\
core/papi.o\
core/partitioner.o\
core/perturb.o\
core/plan4.o\
core/plan5.o\
core/planx.o\
core/postpro.o\
core/prepost.o\
core/reader_par.o\
core/reader_re2.o\
core/reader_rea.o\
core/speclib.o\
core/ssolv.o\
core/subs1.o\
core/subs2.o\
core/vprops.o\

