SETTINGS=

SETTINGS+=" --fileSamp ../final_obs_1act.dat"
SETTINGS+=" --gamma 0.8"
SETTINGS+=" --learnrate 0.001"
SETTINGS+=" --nnl1 32"
SETTINGS+=" --nnl2 32"
SETTINGS+=" --nnl3 0"
SETTINGS+=" --nnType 1"
SETTINGS+=" --greedyeps 0.0"
SETTINGS+=" --nnL 0.0000"
SETTINGS+=" --bTrain 0"
SETTINGS+=" --rType 5"
SETTINGS+=" --senses 0"
SETTINGS+=" --learn NA"
SETTINGS+=" --dqnBatch 50"
SETTINGS+=" --dqnT 0.001"
