#!/bin/bash -l

#SBATCH --job-name=DPG_split_effects
#SBATCH --time=24:00:00
#SBATCH --output=out.%j.%a.o
#SBATCH --error=out.%j.%a.e
#SBATCH --constraint=gpu
# #SBATCH --partition=debug

# #SBATCH --account=ch7
#SBATCH --account=s658
# #SBATCH --account=eth2

#SBATCH --array=0-599

# #SBATCH --ntasks=1
# #SBATCH --ntasks-per-node=1

# ======START=====
COMMNAME=DPG_split_effects

SETTINGS=" --gamma 0.995 --nnl1 128 --nnl2 128 --nnFunc SoftSign --learner DPG --minTotObsNum 262144 --targetDelay 0.01 --explNoise 0.2 --totNumSteps 10000000 --learnrate 0.00001 --nMasters 1 --nThreads 12 --outWeightsPrefac 0.1 --epsAnneal 5e-7 --batchSize 128 --obsPerStep 1 --ERoldSeqFilter oldest"

MYNAME=`whoami`
SMARTIESDIR="${HOME}/smarties/"
BASEPATH="/scratch/snx3000/${MYNAME}/smarties/"
TOLPARAM=(0.10)
BUFFSIZE=(262144 1048576)

IMPSAMPR=(2 5 2 5 2 5)
REFER=(0.1 0.1 1.1 1.1 2.1 2.1)
FUNC=(Tanh Tanh Tanh Tanh Tanh Tanh)
SAMP=(uniform uniform uniform uniform uniform uniform)

#RUNTRIAL=(0 1 2 3 4 5 6 7 8 9)
RUNTRIAL=(1 2 3 4 5)

TASKNAME=(HumanoidStandup-v2 Humanoid-v2 Ant-v2 Walker2d-v2 HalfCheetah-v2 Reacher-v2 Swimmer-v2 Hopper-v2 InvertedPendulum-v2 InvertedDoublePendulum-v2)
SHORTID=( standu             humanw      spider walker      cheeta         reachr     swimmr     hopper    invpnd              dblpnd)

cases=()
rundir=()
appspec=()
#approximatively sorted by strongest effect on runtime
for it in `seq 0 ${#TASKNAME[@]}`; do

for d in ${TOLPARAM[@]}; do
for n in ${BUFFSIZE[@]}; do
#for ic in `seq 0 ${#IMPSAMPR[@]}`; do
for ic in `seq 0 5`; do

for r in ${RUNTRIAL[@]}; do

c=${IMPSAMPR[$ic]}
e=${REFER[$ic]}
f=${FUNC[$ic]}
s=${SAMP[$ic]}

cases+=(" --maxTotObsNum $n --clipImpWeight $c --penalTol $d --nnOutputFunc $f --nnPdrop $e --dataSamplingAlgo $s ")
rundir+=("${SHORTID[$it]}_${COMMNAME}_N${n}_R${c}_F${f}_E${e}_S${s}_TRIAL${r}")
appspec+=("${TASKNAME[$it]}")

done

done
done
done

done

# stuff that depends on SLURM_ARRAY_TASK_ID
RUNFOLDER=${rundir[$SLURM_ARRAY_TASK_ID]}

RUNPATH=${BASEPATH}${RUNFOLDER}

mkdir -p ${RUNPATH}

RUNSET=${SETTINGS}${cases[$SLURM_ARRAY_TASK_ID]}

cat <<EOF >${RUNPATH}/launchSim.sh
python3 ../Communicator_gym.py \$1 ${appspec[$SLURM_ARRAY_TASK_ID]}
EOF
cat <<EOF >${RUNPATH}/factory
Environment exec=../launchSim.sh n=1
EOF
chmod +x ${RUNPATH}/launchSim.sh

# copy over stuff
cp ${SMARTIESDIR}/makefiles/rl                            ${RUNPATH}/exec
cp ${SMARTIESDIR}/source/Communicators/Communicator.py     ${RUNPATH}/
cp ${SMARTIESDIR}/source/Communicators/Communicator_gym.py ${RUNPATH}/
cp $0                                                      ${RUNPATH}/launch.sh
#git log | head  >                                         ${RUNPATH}/gitlog.log
#git diff >                                                ${RUNPATH}/gitdif.log

cd ${RUNPATH}

export MPICH_MAX_THREAD_SAFETY=multiple
export OMP_NUM_THREADS=12
export OMP_PROC_BIND=TRUE
export OMP_PLACES=cores
export CRAY_CUDA_MPS=1

srun --ntasks 1 --ntasks-per-node=1 ./exec ${RUNSET}

#srun  -n 2 --cpu_bind=map_cpu:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17 ./run1 & srun  -n 2 --cpu_bind=map_cpu:18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35 ./run2 & wait

# =====END====
