#!/bin/bash -l

#SBATCH --account=s658
#SBATCH --job-name="/scratch/daint/novatig/smarties/prova_2act_newLaunch"
#SBATCH --output=/scratch/daint/novatig/smarties/prova_2act_newLaunch_%j.txt
#SBATCH --error=/scratch/daint/novatig/smarties/prova_2act_newLaunch_%j.txt
#SBATCH --time=24:00
#SBATCH --nodes=200
# #SBATCH --partition=viz
#SBATCH --ntasks-per-node=2

module load slurm
module swap PrgEnv-cray PrgEnv-gnu
module swap gcc/4.8.2 gcc/4.9.2
export OMP_NUM_THREADS=8

run.sh 200 2 8
