SETTINGS=

SETTINGS+=" --gamma 0.8"
SETTINGS+=" --learnrate 0.00001"
SETTINGS+=" --nnl1 32"
SETTINGS+=" --nnl2 32"
SETTINGS+=" --nnl3 0"
SETTINGS+=" --nnL 0.0000"
SETTINGS+=" --nnType 1"
SETTINGS+=" --greedyeps 0.0"
SETTINGS+=" --bTrain 1"
SETTINGS+=" --rType 0"
SETTINGS+=" --senses 0"
SETTINGS+=" --learn NA"
SETTINGS+=" --dqnBatch 10"
SETTINGS+=" --dqnT 0.0001"
