SETTINGS=

SETTINGS+=" --gamma 0.99"
SETTINGS+=" --learnrate 0.001"
SETTINGS+=" --nnl1 48"
SETTINGS+=" --nnl2 12"
SETTINGS+=" --nnl3 0"
SETTINGS+=" --nnType 0"
SETTINGS+=" --nnL 0.0001"
SETTINGS+=" --greedyeps 0.2"
SETTINGS+=" --bTrain 0"
SETTINGS+=" --rType 1"
SETTINGS+=" --senses 4"
SETTINGS+=" --learn NAF"
SETTINGS+=" --dqnBatch 100"
SETTINGS+=" --dqnT 0.0001"
