SETTINGS=

SETTINGS+=" --gamma 0.9"
SETTINGS+=" --learnrate 0.000001"
SETTINGS+=" --nnl1 32"
SETTINGS+=" --nnl2 32"
SETTINGS+=" --nnl3 0"
SETTINGS+=" --nnType 1"
SETTINGS+=" --nnL 0.00"
SETTINGS+=" --greedyeps 0.0"
SETTINGS+=" --bTrain 1"
SETTINGS+=" --rType 1"
SETTINGS+=" --senses 0"
SETTINGS+=" --learn NA"
SETTINGS+=" --dqnBatch 10"
SETTINGS+=" --dqnT 1000"
