SETTINGS=

SETTINGS+=" --fileSamp history.txt"
SETTINGS+=" --gamma 0.8"
SETTINGS+=" --learnrate 0.0001"
SETTINGS+=" --nnl1 48"
SETTINGS+=" --nnl2 32"
SETTINGS+=" --nnl3 8"
SETTINGS+=" --nnType 1"
SETTINGS+=" --greedyeps 1.0"
SETTINGS+=" --bTrain 1"
SETTINGS+=" --rType 1"
SETTINGS+=" --senses 3"
SETTINGS+=" --learn NA"
SETTINGS+=" --dqnBatch 10"
SETTINGS+=" --dqnT 0.000001"
