SETTINGS=

SETTINGS+=" --fileSamp ../history_2act.txt"
SETTINGS+=" --gamma 0.9"
SETTINGS+=" --learnrate 0.000001"
SETTINGS+=" --nnl1 32"
SETTINGS+=" --nnl2 32"
SETTINGS+=" --nnl3 32"
SETTINGS+=" --nnType 1"
SETTINGS+=" --greedyeps 0.0"
SETTINGS+=" --bTrain 1"
SETTINGS+=" --rType 1"
SETTINGS+=" --senses 0"
SETTINGS+=" --learn NA"
SETTINGS+=" --dqnBatch 12"
SETTINGS+=" --dqnT 1000"
