SETTINGS=

SETTINGS+=" --fileSamp history.txt"
SETTINGS+=" --gamma 0.9"
SETTINGS+=" --learnrate 0.001"
SETTINGS+=" --nnl1 24"
SETTINGS+=" --nnl2 24"
SETTINGS+=" --nnl3 24"
SETTINGS+=" --nnType 1"
SETTINGS+=" --greedyeps 0.9"
SETTINGS+=" --bTrain 1"
#SETTINGS+=" --rType 1"
SETTINGS+=" --senses 0"
SETTINGS+=" --learn NA"
SETTINGS+=" --dqnBatch 100"
SETTINGS+=" --dqnT 0.0001"
