SETTINGS=

SETTINGS+=" --fileSamp history.txt"
SETTINGS+=" --gamma 0.9"
SETTINGS+=" --learnrate 0.001"
SETTINGS+=" --nnl1 96"
SETTINGS+=" --nnl2 48"
SETTINGS+=" --nnl3 24"
SETTINGS+=" --nnType 1"
SETTINGS+=" --greedyeps 0.0"
SETTINGS+=" --bTrain 0"
SETTINGS+=" --rType 1"
SETTINGS+=" --senses 1"
SETTINGS+=" --learn NA"
SETTINGS+=" --dqnBatch 200"
SETTINGS+=" --dqnT 0.0001"
