SETTINGS=

#SETTINGS+=" --fileSamp ../final_obs_1act.dat"
SETTINGS+=" --gamma 0.8"
SETTINGS+=" --learnrate 0.001"
SETTINGS+=" --nnl1 32"
SETTINGS+=" --nnl2 32"
SETTINGS+=" --nnl3 32"
SETTINGS+=" --nnType 1"
SETTINGS+=" --greedyeps 0.1"
SETTINGS+=" --nnL 0.00001"
SETTINGS+=" --bTrain 1"
SETTINGS+=" --rType 0"
SETTINGS+=" --senses 0"
SETTINGS+=" --learn NAF"
SETTINGS+=" --dqnBatch 50"
SETTINGS+=" --dqnT 1000"
