SETTINGS=

SETTINGS+=" --fileSamp ../final_obs_1act.dat"
SETTINGS+=" --gamma 0.8"
SETTINGS+=" --learnrate 0.0001"
SETTINGS+=" --nnl1 32"
SETTINGS+=" --nnl2 32"
SETTINGS+=" --nnl3 32"
SETTINGS+=" --nnType 0"
SETTINGS+=" --greedyeps 0.0"
SETTINGS+=" --nnL 0.0001"
SETTINGS+=" --bTrain 0"
SETTINGS+=" --rType 1"
SETTINGS+=" --senses 0"
SETTINGS+=" --learn NA"
SETTINGS+=" --dqnBatch 100"
SETTINGS+=" --dqnT 0.0001"
