SETTINGS=

SETTINGS+=" --gamma 0.9"
SETTINGS+=" --learnrate 0.0001"
SETTINGS+=" --nnl1 96"
SETTINGS+=" --nnl2 48"
SETTINGS+=" --nnl3 24"
SETTINGS+=" --nnL 0.0"
SETTINGS+=" --nnType 1"
SETTINGS+=" --greedyeps 0.0"
SETTINGS+=" --bTrain 0"
SETTINGS+=" --rType 0"
SETTINGS+=" --senses 4"
SETTINGS+=" --learn NA"
SETTINGS+=" --dqnBatch 1000"
SETTINGS+=" --dqnT 0.0001"
